name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '*'

jobs:
  tests:
    env:
      PYTHON: '3.9'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Set Spark env
        run: |
          export SPARK_LOCAL_IP=127.0.0.1
          export SPARK_SUBMIT_OPTS="--illegal-access=permit -Dio.netty.tryReflectionSetAccessible=true"

      - name: Generate coverage report
        working-directory: ./
        run: |
          pip install -r requirements.txt
          pip install pyspark==3.1.2 pandas==1.4.2 numpy==1.22.4 coverage
          coverage run -m unittest discover -s tests -p 'tests_*.py'
          coverage xml
          
      - name: Publish test coverage
        uses: codecov/codecov-action@v1